function [ER ev] ...
    = cvtTestMDA(TRAIN_DATA, TRAIN_LABEL, TEST_DATA, TEST_LABEL, PCA_DIM_or_CONTRIBUTION_RATE)

TRAIN_DATA = TRAIN_DATA(:, :);
TEST_DATA = TEST_DATA(:, :);
TRAIN_LABEL = TRAIN_LABEL(:);
TEST_LABEL = TEST_LABEL(:);

[TRAIN_Y V0 D K] = orzPCA(TRAIN_DATA, PCA_DIM_or_CONTRIBUTION_RATE);
[TRAIN_Y V1] = cvtMDA(TRAIN_Y, TRAIN_LABEL, PCA_DIM_or_CONTRIBUTION_RATE);

nClass = max(TRAIN_LABEL(:));
M = cvtClassMean(TRAIN_Y, TRAIN_LABEL);

TEST_Y = V1'*V0'*TEST_DATA;
Dist = cvtL2Norm(M, TEST_Y);
[var PREDICT_LABEL] = min(Dist,[],1);
PREDICT_LABEL = PREDICT_LABEL(:);

% ER
ER = mean(PREDICT_LABEL == TEST_LABEL);

% EER
% ev = OrzEval(Dist, TEST_LABEL', 'D');

end
